### ISSUE TITLE
Lists have huge margins, even on nested lists

### ISSUE THREAD

**Issue by brunnerh** [armadillica/dillo#163]
Example:

![image](https://user-images.githubusercontent.com/834235/123014972-a24f7100-d3c7-11eb-9b17-3d72198a7961.png)

The responsible rule:

```css
.entity-content ul,
.entity-content ol {
    margin-bottom: 3rem;
}
```

`3rem` seems a bit large in any case, but especially for nested lists there should not be that much of a gap.

---

On the other hand, the bottom margin of the items does not create a gap before nested lists, so maybe `ul`/`ol` that are descendants of lists should have an equivalent top margin added:
![image](https://user-images.githubusercontent.com/834235/123015471-c3649180-d3c8-11eb-9d75-6e916ec2db99.png)
